### ISSUE TITLE
Cannot clone on windows due to a filename with "?" in it

### ISSUE THREAD

**Issue by Res260** [ibmresilient/resilient-python-api#22]
## Description
![image](https://user-images.githubusercontent.com/14599855/145480014-f7ad9855-9887-4346-8a8b-b7285948ede8.png)

## Describe How to Reproduce
Clone the current repo on Windows. NTFS file names cannot have a "?" char in it :(

**Comment by Res260** [comment]
Problematic file: https://github.com/ibmresilient/resilient-python-api/blob/master/docs/_static/IBM_Security_Shield.ico%3F

**Comment by sjcurtinibm** [comment]
Hi @Res260, thank you for bringing this to our attention - we have just addressed this and hopefully it resolves your issue! Apologies for any inconvenience!
