### ISSUE TITLE
Usage of num_workers in separate resilient-circuits instances

### ISSUE THREAD

**Issue by poleshe** [ibmresilient/resilient-python-api#30]
Greetings, team!

Not an issue, apologies, but a question.

How does num_workers work if we do not have a central resilient-circuits daemon, but instead an instance for each integration? 

Similar to the AppHost containing each integration in it's own container. Does it mean that if we assign num_workers to 50, we can consume 50 events from the queue and handle them in paral·lel? Or it does not apply in singular instaces?

We tried looking for documentation but couldn't find any

Thanks for your help! Have a nice day!

**Comment by bobleckelibm** [comment]
Hi @poleshe -- your idea of consuming 50 events in parallel is about correct. Let's say, for example, that you have one app with one function with `num_workers=50` running in an isolated app host environment. If you somehow trigger that one function 50 times exactly at the same time, they should all process in relatively close to parallel time and return their results at or around the same time (assuming same run time for each instance of the function). Now this is all theoretical... There may be hardware limits that might impede the processing happening all in the same time, however, the idea still holds. In the case that you have an app running in an isolated (read: AppHost) environment, you should be able to up `num_workers` and see an increase in parallel processing.

Marking this as closed for now, but let me know if you have further questions. Thanks!
