### ISSUE TITLE
Exception Raise on Patch - ValueError: invoked callback did not change the patch object, but returned True

### ISSUE THREAD

**Issue by poleshe** [ibmresilient/resilient-python-api#33]
## Description
Greetings! Happy new year!

Sometimes, when we patch a Resilient Incident, and the information sent is the the same as the existing Incident, we get the following Exception:

ValueError: invoked callback did not change the patch object, but returned True

Please, could we have more insights about this Exception? Is it okay to raise and exception, or perhaps a warning would suffice here? Is this calculated before the request is sent or after? 

Thanks team :)

## Describe How to Reproduce
* Create a Resilient Incident
* Via API, create a patch object for the given Incident. 
* Do not apply any changes to any field, and send the patch request.
* ValueError: invoked callback did not change the patch object, but returned True

Cheers,

**Comment by bobleckelibm** [comment]
Hi @poleshe — happy to help here. Would you be willing to share the specific code that you're using and the wider context logs around the error?

**Comment by poleshe** [comment]
Greetings, @bobleckelibm!

This is the specific part of the code:

https://github.com/ibmresilient/resilient-python-api/blob/3fe752ec5dd72ced0c5a438c09333fafef75f3a8/resilient/resilient/co3.py#L538

I was just wondering if we could get more information. Does it trigger when an error or unwanted http code is returned with the patch? Or just whenever the patch call did not actually change anything in the Incident?

Cheers, thanks a lot!

**Comment by poleshe** [comment]
Greetings!

Okay! That sounds good to me.

Thanks for your help! Have a great day

**Comment by bobleckelibm** [comment]
Sure thing! One more thing to point out is that you should be calling `patch`
https://github.com/ibmresilient/resilient-python-api/blob/3fe752ec5dd72ced0c5a438c09333fafef75f3a8/resilient/resilient/co3.py#L564
rather than directly calling `_handle_patch_response`. Good luck!
